version: '2'
services:
  web:
    image: "node"
    container_name: proxy
    restart: always 
    working_dir: /home/node/app
    command: npm start
    environment:
      - PORT=8080
    ports:
     - "8080:8080"
    volumes:
     - ./:/home/node/app
     