version: "2"
services:
  server:
    image: "node:alpine"
    restart: always
    working_dir: /home/node/app
    command: npm run dev
    environment:
      - PORT=8001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongo:27017
      - MONGO_DATABASE=test
    labels:
      - traefik.backend=py
      - traefik.frontend.rule=Host:py.yuyuko.me
      - traefik.docker.network=proxy
      - traefik.port=8001
    volumes:
      - ./:/home/node/app
    networks:
      - proxy
    ports:
      - 8001:8001
    depends_on:
      - redis
      - mongo
      # - elasticsearch
  redis:
    image: redis:alpine
    restart: always
    networks:
      - proxy
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  #   networks:
  #     - proxy
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
    networks:
      - proxy
    volumes:
      - "mongo-data:/data/db"
    restart: always
volumes:
  redis-data:
  mongo-data:

networks:
  proxy:
    external: true
